# python-targets:
#     - 2
#     - 3

# uses:
#     - flask

pylint:
  disable:
    - bare-except
    - unused-argument
    - pointless-string-statement
    - too-many-locals
    - too-many-arguments
    - protected-access
    - unused-variable
    - super-on-old-class

pep8:
  disable:
    - E1002

ignore-paths:
    - docs
    - quokka/static
    - quokka/babel
    - quokka/templates
    - quokka/mediafiles
    - quokka/translations
    - quokka/themes
    - etc
    - .openshift

requirements:
    - requirements/requirements.txt
    - requirements/test.txt


# doc-warnings: yes
# test-warnings: no
# strictness: veryhigh
# max-line-length: 120
# autodetect: yes
