mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./etc/mongodata:/data/db

web:
    restart: always
    image: quokka/quokkadev
    working_dir: /quokka
    ports:
        - "5000:5000"
    volumes:
        - .:/quokka
    links:
        - mongo:mongo
    command: sh etc/docker_wait_to_start.sh
    environment:
        - QUOKKA_MONGODB_HOST=mongo
        - WAIT_COMMAND=$(nc -zv mongo 27017)
        - WAIT_START_CMD=manage runserver --host 0.0.0.0 --reloader --debug
        - WAIT_SLEEP=3
        - WAIT_LOOPS=50
    mem_limit: 1000000000
