sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - travis_retry pip install -r requirements.txt -r requirements-dev.txt -e .
  - travis_retry pip install coverage coveralls

script: py.test --cov flask_jwt --cov-report term-missing --pep8 --flakes

after_script:
  - coveralls

branches:
  only:
    - master
